## Chapter 6 - Exercise 1: Trực quan hóa dữ liệu Chipotle

#### Cho dữ liệu https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv

Nhà hàng Chipotle là một chuỗi nhà hàng thức ăn nhanh, chuyên cung cấp các món ăn với nguồn gốc từ ẩm thực Mexico. Tại đây khách hàng có thể tùy chọn các thành phần để tạo nên bữa ăn của họ. Nhà hàng cần phân tích dữ liệu bán được trong ngày diễn ra khuyến mãi để có thể điều chỉnh thực đơn và thực hiện các chương trình khuyến mãi phù hợp. Dữ liệu gồm những cột sau:
- order_id: mã đơn hàng
- quantity: số lượng
- item_name: tên món ăn
- choice_description: mô tả món ăn (những yêu cầu thêm)
- item_price: giá bán

Dữ liệu được cung cấp trong file chipotle.tsv, hãy thực hiện các yêu cầu sau:

# Yêu cầu

### Câu 1:
- Đọc dữ liệu và gán vào biến chipo
- Hiển thị 10 dòng đầu của dữ liệu  
- Xem thông tin info()  

### Câu 2:
- a) Đổi kiểu dữ liệu của cột item_price sang kiểu số thực
- b) Tạo cột revenue, với revenue = quantity * item_price

### Câu 3:
- a) Tạo dataframe df gồm 2 cột: tên món ăn và đếm số lần gọi
- b) Sắp xếp df theo tần suất tăng dần, và lấy 5 item cuối cùng  
- c) Vẽ biểu đồ bar chart cho biết 5 món được gọi nhiều lần nhất, có title, xlabel, ylabel và xticks  

### Câu 4:
Nhóm các đơn hàng theo order_id, và tính tổng số lượng gọi và tổng giá trị của mỗi đơn hàng, in kết quả  

### Câu 5:
- a) Từ câu 4, hãy vẽ scatterplot với x là quantity, và y là revenue, có title, xlabel, ylabel. Bạn có nhận xét gì qua biểu đồ này   
- b) Từ biểu đồ ở câu 5a, hãy đặt plt.yscale('log'), xem kết quả và nhận xét.

### Câu 6:
- a) Vẽ barh chart thể hiện 5 món có tổng thành tiền lớn nhất
- b) Vẽ biểu đồ barplot cho biết 5 món được gọi nhiều nhất và trung bình item_price
- c) Vẽ biểu đồ barplot cho biết 5 món được gọi nhiều nhất và trung bình revenue

### Câu 7:
- a) Vẽ histogram của item_price
- b) Vẽ histogram của item_price với bins = 3
- c) Hãy in ra khoảng giá trị item_price và số lần gọi món tương ứng với biểu đồ ở câu 7b

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
# Câu 1: Đọc dữ liệu và gán vào biến chipo

# Hiển thị 10 dòng đầu của dữ liệu

<details>
  <summary style='color:#FD6504; font-size:14px'>Nhấn vào đây để xem kết quả!</summary>
  <div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>order_id</th>
      <th>quantity</th>
      <th>item_name</th>
      <th>choice_description</th>
      <th>item_price</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>1</td>
      <td>1</td>
      <td>Chips and Fresh Tomato Salsa</td>
      <td>NaN</td>
      <td>\$2.39</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>1</td>
      <td>Izze</td>
      <td>[Clementine]</td>
      <td>\$3.39</td>
    </tr>
    <tr>
      <th>2</th>
      <td>1</td>
      <td>1</td>
      <td>Nantucket Nectar</td>
      <td>[Apple]</td>
      <td>\$3.39</td>
    </tr>
    <tr>
      <th>3</th>
      <td>1</td>
      <td>1</td>
      <td>Chips and Tomatillo-Green Chili Salsa</td>
      <td>NaN</td>
      <td>\$2.39</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2</td>
      <td>2</td>
      <td>Chicken Bowl</td>
      <td>[Tomatillo-Red Chili Salsa (Hot), [Black Beans...</td>
      <td>\$16.98</td>
    </tr>
    <tr>
      <th>5</th>
      <td>3</td>
      <td>1</td>
      <td>Chicken Bowl</td>
      <td>[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...</td>
      <td>\$10.98</td>
    </tr>
    <tr>
      <th>6</th>
      <td>3</td>
      <td>1</td>
      <td>Side of Chips</td>
      <td>NaN</td>
      <td>\$1.69</td>
    </tr>
    <tr>
      <th>7</th>
      <td>4</td>
      <td>1</td>
      <td>Steak Burrito</td>
      <td>[Tomatillo Red Chili Salsa, [Fajita Vegetables...</td>
      <td>\$11.75</td>
    </tr>
    <tr>
      <th>8</th>
      <td>4</td>
      <td>1</td>
      <td>Steak Soft Tacos</td>
      <td>[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...</td>
      <td>\$9.25</td>
    </tr>
    <tr>
      <th>9</th>
      <td>5</td>
      <td>1</td>
      <td>Steak Burrito</td>
      <td>[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...</td>
      <td>\$9.25</td>
    </tr>
  </tbody>
</table>
</div>
</details>

In [ ]:
# Xem thông tin info()

In [ ]:
# Câu 2:
# a) Đổi kiểu dữ liệu của cột item_price sang kiểu số thực

# chipo.item_price = chipo.item_price.map(lambda x: float(x[1:]))

In [ ]:
# b) Tạo cột revenue, với revenue = quantity * item_price

In [ ]:
# Câu 3a: tạo dataframe df gồm 2 cột: tên món ăn và đếm số lần gọi

<details>
  <summary style='color:#FD6504; font-size:14px'>Nhấn vào đây để xem kết quả!</summary>
  <table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>item_name</th>
      <th>cnt</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>6 Pack Soft Drink</td>
      <td>54</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Barbacoa Bowl</td>
      <td>66</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Barbacoa Burrito</td>
      <td>91</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Barbacoa Crispy Tacos</td>
      <td>11</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Barbacoa Salad Bowl</td>
      <td>10</td>
    </tr>
  </tbody>
</table>
</details>

In [ ]:
# b) Sắp xếp df theo tần suất tăng dần, và lấy 5 item cuối cùng

In [ ]:
# c) Vẽ biểu đồ bar chart cho biết 5 món được gọi nhiều lần nhất
# (có title, xlabel, ylabel và xticks)

In [ ]:
# Câu 4) Nhóm các đơn hàng theo order_id, và tính tổng số lượng gọi
# và tổng giá trị của mỗi đơn hàng,
# in kết quả

<details>
  <summary style='color:#FD6504; font-size:14px'>Nhấn vào đây để xem kết quả!</summary>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>quantity</th>
      <th>revenue</th>
    </tr>
    <tr>
      <th>order_id</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>1</th>
      <td>4</td>
      <td>11.56</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>33.96</td>
    </tr>
    <tr>
      <th>3</th>
      <td>2</td>
      <td>12.67</td>
    </tr>
    <tr>
      <th>4</th>
      <td>2</td>
      <td>21.00</td>
    </tr>
    <tr>
      <th>5</th>
      <td>2</td>
      <td>13.70</td>
    </tr>
  </tbody>
</table>
</details>

In [ ]:
# Câu 5: Từ câu 4, hãy vẽ scatterplot với x là quantity, và y là revenue, có title, xlabel, ylabel
# Bạn có nhận xét gì qua biểu đồ này

# Thiết lập title và labels

In [ ]:
# b) Từ biểu đồ ở câu 5a, hãy đặt plt.yscale('log'), xem kết quả và nhận xét.



# Thiết lập title và labels

In [ ]:
# Câu 6: vẽ barh chart thể hiện 5 món có tổng thành tiền lớn nhất

In [ ]:
# b) Vẽ biểu đồ barplot cho biết 5 món được gọi nhiều nhất và trung bình item_price

In [ ]:
# c) Vẽ biểu đồ barplot cho biết 5 món được gọi nhiều nhất và trung bình revenue

In [ ]:
# Câu 7a: Vẽ histogram của item_price

In [ ]:
# b) Vẽ histogram của item_price với bins = 3

In [ ]:
# c) Hãy in ra khoảng giá trị item_price và số lần gọi món tương ứng với biểu đồ ở câu 7b

# Nhận thông tin về bins


# In ra giá trị và số lượng của mỗi bin

# Đóng biểu đồ